site_name: ambition-cary's Blogs
site_url: https://ambition-cary.github.io/blogs/
site_author: ambition-cary

nav:
  - 主页: index.md
  - 博客:
    - blog/index.md
    - AST:
      - blog/posts/AST模板.md
    - 浏览器:
      - blog/posts/浏览器知识点.md
  - 标签: tags.md
  - 日志: log/update.md
  - 周刊:
    - weekly/2024.9.23.md
  - 分享:
    - share.md

# 系统预设主题颜色
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant  # 即时加载
    - navigation.instant.prefetch # 即时预取
    - navigation.instant.progress # 即时进度
    - navigation.tracking # 跟踪
    - navigation.tabs # 横向导航栏
    # - navigation.tabs.sticky # 粘性导航栏（固定在顶部）
    - navigation.sections # 目录(目录树)
    - navigation.expand # 目录(目录树)可展开
    - navigation.path # 路径导航
    # - navigation.prune # 目录(目录树)剪枝
    - navigation.indexes # 目录(目录树)索引
    - toc.follow # 目录(目录树)跟随
    # - toc.integrate # 目录(目录树)集成
    - navigation.top # 返回顶部

    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索分享

    # - header.autohide # 隐藏头
    - announce.dismiss # 公告取消按钮

    - navigation.footer # 配置上一页和下一页

    # - content.action.edit # 编辑内容
    # - content.action.view # 查看内容
    - content.code.copy # 代码复制
    - content.code.annotate
    - content.tabs.link
    - content.tooltips





  # 网站logo
  logo: assets/logo.png
  icon:
    logo: material/library
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    tag: 
      MkDocs: material/tag
      ast: material/tag
      browser: material/tag
    # previous: fontawesome/solid/angle-left
    # next: fontawesome/solid/angle-right
  favicon: assets/logo.png

  # 主题字体
  font: 
    text: Roboto
    code: Roboto Mono

  # 主题色系
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 自动切换

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: 赞美太阳
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 赞美黑夜
    
extra_css:
  - css/extra.css
  
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  # - css/404.css

extra_javascript:
  - js/shortcuts.js
  - js/extra.js

copyright: Copyright &copy; 2016 - 2020 Martin Donath

repo_url: https://github.com/ambition-cary/blogs
repo_name: ambition-cary/blogs
edit_uri: edit/main/docs/

extra:
  generator: false
  homepage: https://ambition-cary.github.io/blogs/
  # version:
  #   provider: mike
  #   default: latest
  social:
    - icon: fontawesome/brands/gitlab
      link: ''
    - icon: fontawesome/brands/github 
      link: https://github.com/ambition-cary
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/LiuKai01035373
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/profile.php?id=61557686393650
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/%E5%87%AF-%E5%88%98-2878a92b8/
    
  tags:
    MkDocs: MkDocs
    ast: ast
    browser: browser

plugins:
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date 
      exclude:
        - index.md
  - search
  # - mike:
  #     alias_type: symlink
  #     redirect_template: null
  #     deploy_prefix: ''
  #     canonical_version: null
  #     version_selector: true
  #     css_dir: css
  #     javascript_dir: js
  - blog:
      draft: true
      draft_on_serve: false
      draft_if_future_date: true
      post_date_format: full
      post_readtime: true
      post_readtime_words_per_minute: 265
      post_url_format: "{date}/{slug}"
      pagination_url_format: "page/{page}"

markdown_extensions:
  - tables
  - abbr # 缩写
  - attr_list # 注释
  - admonition # 警告
  - def_list # li列表
  - footnotes # 脚注
  - md_in_html

  - toc: # Table of Contents
      permalink: true
      title: 划重点，要考的！
      permalink_title: 世界聚焦于你

  - pymdownx.tasklist:
      custom_checkbox: true # 任务列表
      # clickable_checkbox: true # 可点击
  - pymdownx.emoji: # 显示表情图标
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.betterem # 优化mk格式识别
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde # 各种高亮、下划线
  - pymdownx.keys # 显示键盘按键图标
  - pymdownx.critic: # 突出标记注释
      mode: view
  - pymdownx.details # 标注可折叠
  - pymdownx.highlight: # 代码块
      anchor_linenums: true
      auto_title: true # 显示语言
      linenums: true # 显示行号
      linenums_style: pymdownx-inline # 显示行号的格式
      line_spans: __span
  - pymdownx.inlinehilite # 行内标注语言 range()
  - pymdownx.snippets
  - pymdownx.smartsymbols # 符号转义
  - pymdownx.tabbed:
      alternate_style: true # tabs并列
      # combine_header_slug: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
